
include ./Makefile.inc

.PHONY: all clean

#all: server client
# Archivos fuente y objetos
SRC := pop3.c main.c
OBJ := $(SRC:.c=.o)

# Regla principal para compilar todo
all: $(TARGET)

# Regla para compilar el ejecutable a partir de los objetos
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(TARGET)

# Regla para compilar archivos objeto individuales
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Regla para limpiar archivos compilados
clean:
	rm -f $(OBJ) $(TARGET)