
include ./Makefile.inc



#all: server client
# Archivos fuente y objetos
SERVER_SOURCES=$(wildcard src/server/*.c)
CLIENT_SOURCES=$(wildcard src/client/*.c)


OUTPUT_FOLDER=./bin
OUTPUT_FILE=$(OUTPUT_FOLDER)/server

# Regla principal para compilar todo
all: server client

# Regla para compilar el ejecutable a partir de los objetos
server:
	mkdir -p $(OUTPUT_FOLDER)
	$(CC) $(CFLAGS) $(SERVER_SOURCES) -o server


# Regla para limpiar archivos compilados
clean:
	rm -f $(OUTPUT_FILE)

.PHONY: all, clean, server, client